schema_version: 1

context:
  version: "0.0.4"

package:
  name: pothenon
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/pothenon/pothenon-${{ version }}.tar.gz
  sha256: 6a332f476b98a9b5442916647385837f456d3423e84b0d445be12aa826d5703a

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling >=1.27.0,<=1.32.3
    - hatch-vcs ==0.5.0
    - pip
  run:
    - python >=${{ python_min }},<3.14
    - pyiron_snippets >=1.2.1,<=1.5.0
    - gitpython >=3.1.50,<=3.1.62
    - networkx >=3.5,<=3.6.1

tests:
  - python:
      imports:
        - pothenon
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: pothenon - dependency parser for python functions
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/pyiron/pothenon
  documentation: https://pothenon.readthedocs.io

extra:
  recipe-maintainers:
    - niklassiemer
